prepare_install &&

install -Dm644 autoload/ack.vim /usr/share/vim/vimfiles/autoload/ack.vim
install -Dm644 plugin/ack.vim /usr/share/vim/vimfiles/plugin/ack.vim

mkdir -p /usr/share/vim/vimfiles/doc/
install -Dm644 doc/ack*.txt /usr/share/vim/vimfiles/doc/

mkdir -p /usr/share/vim/vimfiles/ftplugin/
install -Dm644 ftplugin/*.vim /usr/share/vim/vimfiles/ftplugin/
