prepare_install &&

INST_PATH=/usr/share/vim/vimfiles

install -Dm644 doc/multiple_cursors.txt $INST_PATH/doc/multiple_cursors.txt
install -Dm644 plugin/multiple_cursors.vim $INST_PATH/plugin/multiple_cursors.vim
install -Dm644 autoload/multiple_cursors.vim $INST_PATH/autoload/multiple_cursors.vim
