prepare_install &&

OPTS+=" --sysconfdir=/etc \
        --sbindir=/usr/bin \
        --localstatedir=/var \
        --datarootdir=/usr/share \
        --with-pidfile=/run/openrc-settingsd.pid"

default_build
