OPTS=" --prefix=/usr \
       --enable-array \
       --enable-dirstack \
       --enable-help \
       --enable-history \
       --enable-lineedit \
       --enable-nls \
       --enable-printf \
       --enable-socket \
       --enable-test \
       --enable-ulimit"

./configure $OPTS &&

default_make
