prepare_install &&

install -Dm755 ddgr /usr/bin/ddgr &&
install -Dm644 ddgr.1 /usr/share/man/man1/ddgr.1 &&
install -Dm644 auto-completion/fish/ddgr.fish /usr/share/fish/vendor_completions.d/ddgr.fish &&
install -Dm644 auto-completion/bash/ddgr-completion.bash /etc/bash_completion.d/ddgr &&
install -Dm644 auto-completion/zsh/_ddgr /usr/share/zsh/site-functions/_ddgr
