prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

install -d $INSTPTH/{plugin,doc,autoload}
install -D -m644 autoload/delimitMate.vim $INSTPTH/autoload/
install -D -m644 plugin/delimitMate.vim $INSTPTH/plugin/
install -D -m644 doc/delimitMate.txt $INSTPTH/doc/
