#!/bin/bash
# dansguardian  This shell script takes care of starting and stopping
#               dansguardian web content filter
#
# chkconfig: 345 95 5
# description: dansguardian - web content filter
# pidfile: /var/run/dansguardian.pid
# processname: dansguardian
# config: /etc/dansguardian/dansguardian.conf

start() {
    echo -n "Starting dansguardian: "
    /usr/bin/dansguardian 2> /dev/null &&
    echo -e "$RESULT_OK" ||
    echo -e "$RESULT_FAIL"
}

stop() {
    echo -n "Stopping dansguardian: "
    /usr/bin/dansguardian -q &&
    echo -e "$RESULT_OK" ||
    echo -e "$RESULT_FAIL"
}

reload() {
    echo -n "Reloading dansguardian: "
    /usr/bin/dansguardian -g &&
    echo -e "$RESULT_OK" ||
    echo -e "$RESULT_FAIL"
}

status() {
    /usr/bin/dansguardian -s
}

restart() {
    $0 stop
    $0 start
}

case "$1" in
    start|stop|restart|reload|status) ;;
    *) echo "Usage: $0 {start|stop|restart|reload|status}" ; exit 1 ;;
esac

. /lib/lsb/init-functions
