prepare_install &&

install -d /usr/share/vim/vimfiles/{plugin,doc,autoload/sneak} &&
install -D -m644 autoload/sneak/*.vim /usr/share/vim/vimfiles/autoload/sneak/ &&
install -D -m644 plugin/sneak.vim /usr/share/vim/vimfiles/plugin/ &&
install -D -m644 doc/sneak.txt /usr/share/vim/vimfiles/doc/
