prepare_install &&

INSTPTH=/usr/share/nvim/runtime

mkdir -p $INSTPTH/{doc,nerdtree_plugin,plugin,syntax} &&
install -m644 doc/NERD_tree.txt $INSTPTH/doc/ &&
install -m644 plugin/NERD_tree.vim $INSTPTH/plugin/ &&
install -m644 syntax/nerdtree.vim $INSTPTH/syntax/ &&
install -m644 nerdtree_plugin/{exec_menuitem,fs_menu}.vim $INSTPTH/nerdtree_plugin/
