prepare_install &&

echo 'Installing documentation...'
install -Dm 644 README.md /usr/share/doc/vim-auto-pairs/README.md

echo 'Installing appdirs...'
install -dm 755 /usr/share/vim/vimfiles/plugin
install -Dm 644 plugin/*.vim /usr/share/vim/vimfiles/plugin/
