prepare_install &&

echo 'Installing documentation...'
mkdir -p /usr/share/doc/vim-auto-pairs &&
install -Dm 644 README.md /usr/share/doc/vim-auto-pairs/ &&

echo 'Installing appdirs...'
install -dm 755 /usr/share/vim/vimfiles/plugin &&
install -Dm 644 plugin/*.vim /usr/share/vim/vimfiles/plugin/
