prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

install -Dm644 autoload/repl.vim $INSTPTH/autoload/repl.vim
install -Dm644 plugin/repl.vim   $INSTPTH/plugin/repl.vim
install -Dm644 syntax/repl.vim   $INSTPTH/syntax/repl.vim
