prepare_install &&

INST_PATH=/usr/share/vim/vimfiles

mkdir -p $INST_PATH/{doc,plugin} &&
install -Dm 644 doc/indentLine.txt $INST_PATH/doc/ &&
install -Dm 644 after/plugin/indentLine.vim $INST_PATH/plugin/
