prepare_install &&

install -Dm 755 /usr/share/vim/vimfiles/{plugin,autoload} &&
install -m 644 autoload/*.vim /usr/share/vim/vimfiles/autoload/ &&
install -m 644 plugin/shfmt.vim /usr/share/vim/vimfiles/plugin/
