prepare_install &&

install -d /usr/share/vim/vimfiles/{plugin,autoload} &&
install -D -m644 autoload/*.vim /usr/share/vim/vimfiles/autoload/ &&
install -D -m644 plugin/shfmt.vim /usr/share/vim/vimfiles/plugin/
