prepare_install &&

install -d "${pkgdir}/usr/share/vim/vimfiles"
cp -dpr --no-preserve=ownership pythonx /usr/share/vim/vimfiles &&
cp -dpr --no-preserve=ownership doc /usr/share/vim/vimfiles/doc &&
cp -dpr --no-preserve=ownership after /usr/share/vim/vimfiles/after &&
cp -dpr --no-preserve=ownership autoload /usr/share/vim/vimfiles/autoload &&
cp -dpr --no-preserve=ownership ftplugin /usr/share/vim/vimfiles/ftplugin &&
cp -dpr --no-preserve=ownership plugin /usr/share/vim/vimfiles/plugin

