prepare_install &&

cp -dp  --no-preserve=ownership jedi_vim.py initialize.py /usr/share/vim/vimfiles/
cp -dp  --no-preserve=ownership doc/jedi-vim.txt /usr/share/vim/vimfiles/doc/
cp -dpr --no-preserve=ownership after /usr/share/vim/vimfiles/
cp -dpr --no-preserve=ownership autoload /usr/share/vim/vimfiles/
cp -dpr --no-preserve=ownership ftplugin /usr/share/vim/vimfiles/
cp -dpr --no-preserve=ownership plugin /usr/share/vim/vimfiles/
