qmake-qt5 &&

prepare_install &&

default_make

#install -Dm755 qtpass /usr/bin/$MODULE &&
#install -Dm644 artwork/icon.png /usr/share/pixmaps/$MODULE.png &&
#install -Dm644 $MODULE.desktop /usr/share/applications/$MODULE.desktop
