OPTS+=" --enable-pthread \
        --disable-rpath \
        --disable-locking \
        --with-group=usb \
        --with-lockdir=/run/lock/sane \
        --with-docdir=/usr/share/doc/$MODULE"

OPTS+=" --sbindir=/usr/bin"

default_build
