prepare_install &&

install -D -m0644 plugin/better-whitespace.vim /usr/share/vim/vimfiles/plugin/better-whitespace.vim
install -D -m0644 doc/better-whitespace.txt /usr/share/doc/$MODULE/better-whitespace.txt
