OPTS+=" --enable-nc \
        --disable-static \
        --with-pic=yes \
        --with-openssldir=/etc/ssl"

default_build

#install -Dm 755 ./apps/nc/nc /usr/bin/ &&
#ln -sf nc /usr/bin/netcat &&
#install -Dm 644 ./apps/nc/nc.1 /usr/share/man/man1/
