prepare_install &&

install -dm 755 /usr/share/vim/vimfiles/autoload/airline/themes &&
install -m 644 autoload/airline/themes/*.vim /usr/share/vim/vimfiles/autoload/airline/themes/ &&

install -dm 755 /usr/share/vim/vimfiles/autoload/lightline/colorscheme &&
install -m 644 autoload/lightline/colorscheme/*.vim /usr/share/vim/vimfiles/autoload/lightline/colorscheme/

install -dm 755 /usr/share/vim/vimfiles/colors &&
install -m 644 colors/*.vim /usr/share/vim/vimfiles/colors
