prepare_install &&

make PREFIX=/usr install &&

#install -Dm644 contrib/zsh_completion /usr/share/zsh/site-functions/_$MODULE &&
install -Dm644 contrib/bash_completion /usr/share/bash-completion/completions/$MODULE
