OPTS+=" --with-libxklavier \
        --disable-static \
        --disable-libido \
        --disable-libindicator \
        --enable-kill-on-sigterm" &&

OPTS+=" --sbindir=/usr/bin" &&

default_build
