prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

install -D -m0644 plugin/trailing-whitespace.vim $INSTPTH/plugin/trailing-whitespace.vim
install -D -m0644 doc/trailing-whitespace.txt /usr/share/doc/$MODULE/trailing-whitespace.txt
