prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

install -Dm644 autoload/undotree.vim $INSTPTH/autoload/
install -Dm644 plugin/undotree.vim $INSTPTH/plugin/
install -Dm644 syntax/undotree.vim $INSTPTH/syntax/
