prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

mkdir -p $INSTPTH/{autoload,plugin,syntax} &&
install -Dm 644 autoload/undotree.vim $INSTPTH/autoload/ &&
install -Dm 644 plugin/undotree.vim $INSTPTH/plugin/ &&
install -Dm 644 syntax/undotree.vim $INSTPTH/syntax/
