prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

mkdir -p $INSTPTH/autoload &&
install -Dm 644 plug.vim $INSTPTH/autoload/ &&
install -Dm 644 $SCRIPT_DIRECTORY/plug.vimrc /usr/share/vim-plug/vimrc.sample

