prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

install -Dm 644 doc/NERD_commenter.txt "${INSTPTH}/doc/NERD_commenter.txt" &&
install -Dm 644 plugin/NERD_commenter.vim "${INSTPTH}/plugin/NERD_commenter.vim"
