prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

mkdir -p $INSTPTH/{plugin,doc,autoload/tablemode} &&
install -Dm 644 doc/tagbar.txt $INSTPTH/doc/ &&
install -Dm 644 autoload/tagbar.vim $INSTPTH/autoload/ &&
install -Dm 644 plugin/tagbar.vim $INSTPTH/plugin/ &&
install -Dm 644 syntax/tagbar.vim $INSTPTH/syntax/
