prepare_install &&

INSTPTH=/usr/share/nvim/runtime

mkdir -p $INSTPTH/{plugin,doc,autoload/tablemode} &&
install -Dm 644 doc/tagbar.txt $INSTPTH/doc/tagbar.txt &&
install -Dm 644 autoload/tagbar.vim $INSTPATH/autoload/tagbar.vim &&
install -Dm 644 plugin/tagbar.vim $INSTPATH/plugin/tagbar.vim &&
install -Dm 644 syntax/tagbar.vim $INSTPATH/syntax/tagbar.vim

