prepare_install &&

mkdir -p /usr/share/doc/i3-volume &&
install -Dm755 volume /usr/bin/i3-volume &&
install -Dm644 README.md /usr/share/doc/i3-volume/ &&
install -Dm644 "${SCRIPT_DIRECTORY}"/i3volume-alsa.conf /usr/share/doc/i3-volume/ &&
install -Dm644 "${SCRIPT_DIRECTORY}"/i3volume-pulseaudio.conf /usr/share/doc/i3-volume/
