OPTS+=" --with-threads \
        --disable-debug \
        --disable-static \
        --disable-debug-api \
        --with-python=/usr/bin/python2"

sedit 's_#!/usr/bin/env python_#!/usr/bin/env python2_' python/gamin.py &&

default_build
