prepare_install &&

mkdir -p /usr/share/vim/vimfiles/plugin/ &&
install -D -m 644 plugin/better-whitespace.vim /usr/share/vim/vimfiles/plugin/ &&

mkdir -p /usr/share/doc/$MODULE/ &&
install -D -m 644 doc/better-whitespace.txt /usr/share/doc/$MODULE/
