prepare_install &&

INSTPATH=/usr/share/vim/vimfiles

mkdir -p $INSTPATH &&
install -Dm644 plugin/dirdiff.vim /usr/share/vim/vimfiles/plugin/dirdiff.vim
install -Dm644 doc/dirdiff.txt    /usr/share/vim/vimfiles/doc/dirdiff.txt
