prepare_install &&

mkdir -p /usr/share/vim/vimfiles/{plugin,doc,autoload} &&
cp -r plugin/* /usr/share/vim/vimfiles/plugin/ &&
cp doc/editorconfig.txt /usr/share/vim/vimfiles/doc/ &&
cp autoload/editorconfig.vim /usr/share/vim/vimfiles/autoload/
