export CXXFLAGS="$CXXFLAGS -fpermissive"

chmod 755 configure

OPTS+=" --enable-default-catalog=/usr/share/sgml/catalog"

default_build &&

mv /usr/bin/sx /usr/bin/sgml2xml &&

rm /usr/lib/lib{grove,sp,spgrove,style}.a
