prepare_install &&

INSTPTH=/usr/share/vim/vimfiles

install -dm755  &&
install -d $INSTPTH/{doc,plugin}
install -Dm644 doc/unimpaired.txt $INSTPTH/doc/unimpaired.txt
install -Dm644 plugin/unimpaired.vim $INSTPTH/plugin/unimpaired.vim
