prepare_install &&

mkdir -p /usr/share/vim/vimfiles/colors/ &&
install -m 755 gruvbox_256palette.sh /usr/share/vim/vimfiles/colors/ &&
install -m 644 colors/gruvbox.vim /usr/share/vim/vimfiles/colors/
