prepare_install &&

INSTPTH=/usr/share/exvim

mkdir -p $INSTPTH &&
cp -r * .vimrc .vimrc.mini .vimrc.plugins $INSTPTH

echo "Replace your ~/.vimrc:"
echo "Let g:exvim_custom_path=$INSTPTH"
echo "Source $INSTPTH/.vimrc"
