prepare_install &&

python setup.py install --root="/" --optimize=1 &&

mv "/usr/share/bash-completion/completions/youtube-dl.bash-completion" \
   "/usr/share/bash-completion/completions/youtube-dl"
