prepare_install &&

local INSTPTH=/usr/share/vim/vimfiles

install -dm755 $INSTPTH/plugin/assistant
install -Dm644 plugin/assistant.vim $INSTPTH/plugin/
install -Dm644 plugin/assistant/* $INSTPTH/plugin/assistant
