OPTS+=" --sbindir=/usr/bin"

default_build

#if module_installed systemd; then
#  install -Dm0644 $SCRIPT_DIRECTORY/sshguard.service /usr/lib/systemd/system/sshguard.service &&
#  install -Dm0755 $SCRIPT_DIRECTORY/sshguard-journalctl /usr/lib/systemd/scripts/sshguard-journalctl
#fi
