prepare_install &&

# nord colorscheme
install -Dm644 colors/nord.vim /usr/share/vim/vimfiles/colors/nord.vim

# nord colorscheme for airline
install -Dm644 autoload/airline/themes/nord.vim /usr/share/vim/vimfiles/autoload/airline/themes/nord.vim

# nord clolorcscheme for lightline
install -Dm644 autoload/lightline/colorscheme/nord.vim /usr/share/vim/vimfiles/autoload/lightline/colorscheme/nord.vim
